commit_message: "Chore: Localization updates for %original_file_name% [no ci]"
append_commit_message: false

files:
    # Plugin
  - source: /XIVITAGuide/Resources/Localization/Plugin/*_Localizable.json
    translation: /%original_path%/%two_letters_code%.json
    # A Realm Reborn
  - source: /XIVITAGuide/Resources/Localization/Guide/v1/en/A Realm Reborn/Dungeons
    translation: /XIVITAGuide/Resources/Localization/Guide/v1/%two_letters_code%/A Realm Reborn/Dungeons/%original_file_name%
  - source: /XIVITAGuide/Resources/Localization/Guide/v1/en/A Realm Reborn/AllianceRaids
    translation: /XIVITAGuide/Resources/Localization/Guide/v1/%two_letters_code%/A Realm Reborn/Alliance Raids/%original_file_name%
  - source: /XIVITAGuide/Resources/Localization/Guide/v1/en/A Realm Reborn/Trials
    translation: /XIVITAGuide/Resources/Localization/Guide/v1/%two_letters_code%/A Realm Reborn/Trials/%original_file_name%
    # Heavensward
  - source: /XIVITAGuide/Resources/Localization/Guide/v1/en/Heavensward/Dungeons
    translation: /XIVITAGuide/Resources/Localization/Guide/v1/%two_letters_code%/Heavensward/Dungeons/%original_file_name%
  - source: /XIVITAGuide/Resources/Localization/Guide/v1/en/Heavensward/AllianceRaids
    translation: /XIVITAGuide/Resources/Localization/Guide/v1/%two_letters_code%/Heavensward/Alliance Raids/%original_file_name%
  - source: /XIVITAGuide/Resources/Localization/Guide/v1/en/Heavensward/Trials
    translation: /XIVITAGuide/Resources/Localization/Guide/v1/%two_letters_code%/Heavensward/Trials/%original_file_name%
    # Stormblood
  - source: /XIVITAGuide/Resources/Localization/Guide/v1/en/Stormblood/Dungeons
    translation: /XIVITAGuide/Resources/Localization/Guide/v1/%two_letters_code%/Stormblood/Dungeons/%original_file_name%
  - source: /XIVITAGuide/Resources/Localization/Guide/v1/en/Stormblood/AllianceRaids
    translation: /XIVITAGuide/Resources/Localization/Guide/v1/%two_letters_code%/Stormblood/Alliance Raids/%original_file_name%
  - source: /XIVITAGuide/Resources/Localization/Guide/v1/en/Stormblood/Trials
    translation: /XIVITAGuide/Resources/Localization/Guide/v1/%two_letters_code%/Stormblood/Trials/%original_file_name%
    # Shadowbringers
  - source: /XIVITAGuide/Resources/Localization/Guide/v1/en/Shadowbringers/Dungeons
    translation: /XIVITAGuide/Resources/Localization/Guide/v1/%two_letters_code%/Shadowbringers/Dungeons/%original_file_name%
  - source: /XIVITAGuide/Resources/Localization/Guide/v1/en/Shadowbringers/AllianceRaids
    translation: /XIVITAGuide/Resources/Localization/Guide/v1/%two_letters_code%/Shadowbringers/Alliance Raids/%original_file_name%
  - source: /XIVITAGuide/Resources/Localization/Guide/v1/en/Shadowbringers/Trials
    translation: /XIVITAGuide/Resources/Localization/Guide/v1/%two_letters_code%/Shadowbringers/Trials/%original_file_name%
    # Endwalker
  - source: /XIVITAGuide/Resources/Localization/Guide/v1/en/Endwalker/Dungeons
    translation: /XIVITAGuide/Resources/Localization/Guide/v1/%two_letters_code%/Endwalker/Dungeons/%original_file_name%
  - source: /XIVITAGuide/Resources/Localization/Guide/v1/en/Endwalker/AllianceRaids
    translation: /XIVITAGuide/Resources/Localization/Guide/v1/%two_letters_code%/Endwalker/Alliance Raids/%original_file_name%
  - source: /XIVITAGuide/Resources/Localization/Guide/v1/en/Endwalker/Trials
    translation: /XIVITAGuide/Resources/Localization/Guide/v1/%two_letters_code%/Endwalker/Trials/%original_file_name%
