name: "PR: Code Changes"

on:
  pull_request:
    branches: [main]
    paths:
      - "XIVITAGuide/**.cs"
      - "XIVITAGuide/**.csproj"
    types: [ready_for_review, opened, synchronize]

jobs:
  Build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@dc323e67f16fb5f7663d20ff7941f27f5809e9b6 # v2

      - name: Set up .NET
        uses: actions/setup-dotnet@608ee757cfcce72c2e91e99aca128e0cae67de87 # v1
        with:
          dotnet-version: 6.0.x

      - name: Restore Dependencies
        working-directory: XIVITAGuide/
        run: dotnet restore

      - name: Download Dalamud Library
        run: |
          wget https://goatcorp.github.io/dalamud-distrib/latest.zip -O /tmp/dalamud.zip
          unzip /tmp/dalamud.zip -d /tmp/dalamud

      - name: Build Plugin (Dev)
        working-directory: XIVITAGuide/
        run: dotnet build
        env:
          DALAMUD_HOME: /tmp/dalamud
          IsCI: true

      - name: Build Plugin (Release)
        working-directory: XIVITAGuide/
        run: dotnet build --configuration Release
        env:
          DALAMUD_HOME: /tmp/dalamud
          IsCI: true

      - name: Upload Artifacts
        uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb # v3
        with:
          name: build
          path: ./XIVITAGuide/bin
