name: "PR: JSON Changes"

on:
  pull_request:
      branches: [main]
      paths:
       - '**.json'

jobs:
  Validate:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Validate JSON Syntax
        uses: limitusus/json-syntax-check@v2
        with:
          pattern: "\\.json$"
