---
name: Build & Deploy
on:
  push:
    tags:
      - v*.*.*.*
env:
  SOLUTION_NAME: XIVITAGuide
  INTERNAL_NAME: XIVITAGuide
  RELEASE_DIR: XIVITAGuide/bin/x64/Release/XIVITAGuide
  XIVITA_REPO_URL: ffxivita/DalamudPlugins
  DOTNET_CLI_TELEMETRY_OPTOUT: true
jobs:
  BuildPlugin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3
        with:
          fetch-depth: 0
      - name: Set up .NET
        uses: actions/setup-dotnet@608ee757cfcce72c2e91e99aca128e0cae67de87 # v1
        with:
          dotnet-version: 6.0.x
      - name: Restore Dependencies
        run: dotnet restore
      - name: Download Dalamud Library
        run: >
          wget https://goatcorp.github.io/dalamud-distrib/latest.zip -O
          /tmp/dalamud.zip

          unzip /tmp/dalamud.zip -d /tmp/dalamud
      - name: Get Tag Name
        id: tag_name
        shell: bash
        run: echo "::set-output name=TAG::$(echo ${{ github.ref }} | sed
          's/refs\/tags\///' | sed 's/v//')"
      - name: Build Plugin
        shell: bash
        run: >
          dotnet build --configuration Release --nologo -p:AssemblyVersion=${{
          steps.tag_name.outputs.TAG }} -p:AssemblyInformationalVersion=${{
          steps.tag_name }}

          sha512sum XIVITAGuide/bin/x64/Release/XIVITAGuide/latest.zip  >> checksums.txt

          sha512sum XIVITAGuide/bin/x64/Release/XIVITAGuide/XIVITAGuide.json >> checksums.txt

          cat checksums.txt
        env:
          DALAMUD_HOME: /tmp/dalamud
          IsCI: true
      - name: UploadArtifact
        uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb # v3
        with:
          name: ${{ env.INTERNAL_NAME }}
          path: ${{ env.RELEASE_DIR }}
  Upload:
    needs: BuildPlugin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3
        with:
          path: plugins/
          repository: ${{ env.XIVITA_REPO_URL }}
          token: ${{ secrets.PAT }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Download
        uses: actions/download-artifact@9782bd6a9848b53b110e712e20e42d89988822b7 # v3
        with:
          name: XIVITAGuide
          paths: plugins/${{ env.INTERNAL_NAME }}
          pathspec_error_handling: exitImmediately
      - name: Commit
        uses: EndBug/add-and-commit@61a88be553afe4206585b31aa72387c64295d08b # v9
        with:
          author_name: Priscilla(XIVITA)
          author_email: noreply@ahd-creative.agency
          message: Aggiornamento di ${{ env.INTERNAL_NAME }} pronto!
