name: Build & Deploy

on:
  push:
    tags:
      - "v*.*.*.*"

env:
  SOLUTION_NAME: XIVITAGuide
  INTERNAL_NAME: XIVITAGuide
  RELEASE_DIR: XIVITAGuide\bin\Release\XIVITAGuide
  XIVITA_REPO_URL: ffxivita/DalamudPlugins
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  BuildPlugin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Download Dalamud Library
        run: |
          wget https://goatcorp.github.io/dalamud-distrib/latest.zip -O /tmp/dalamud.zip
          unzip /tmp/dalamud.zip -d /tmp/dalamud

      - name: Get Tag Name
        id: tag_name
        shell: bash
        run: >-
          echo "::set-output name=TAG::$(echo ${{ github.ref }} | sed 's/refs\/tags\///' | sed 's/v//')"

      - name: Build Plugin
        shell: bash
        run: |
          dotnet build --configuration Release --nologo -p:AssemblyVersion=${{ steps.tag_name.outputs.TAG }} -p:AssemblyInformationalVersion=${{ steps.tag_name }}
          sha512sum XIVITAGuide/bin/x64/Release/XIVITAGuide/latest.zip  >> checksums.txt
          sha512sum XIVITAGuide/bin/x64/Release/XIVITAGuide/XIVITAGuide.json >> checksums.txt
          cat checksums.txt
        env:
          DALAMUD_HOME: /tmp/dalamud
          IsCI: true

  Upload:
    needs: BuildPlugin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          add: plugins/
          ref: main
          repository: ${{ env.XIVITA_REPO_URL }}
          token: ${{ secrets.PAT }}
      - name: Download
        uses: actions/download-artifact@v2
        with:
          name: XIVITAGuide
          path: plugins/${{ env.INTERNAL_NAME }}
          pathspec_error_handling: exitImmediately
      - name: Commit
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Priscilla(XIVITA)
          author_email: noreply@ahd-creative.agency
          message: Aggiornamento di ${{ env.INTERNAL_NAME }} pronto!
    