name: Build & Deploy

on:
  push:
    tags:
      - "v*.*.*.*"

env:
  SOLUTION_NAME: XIVITAGuide
  INTERNAL_NAME: XIVITAGuide
  RELEASE_DIR: XIVITAGuide\bin\Release\XIVITAGuide
  XIVITA_REPO_URL: ffxivita/DalamudPlugins
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  
jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup Build
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Download Dalamud Library
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev\"
      - name: Build Plugin
        run: |
          dotnet restore -r win ${{ env.SOLUTION_NAME }}.sln
          dotnet build ${{ env.SOLUTION_NAME }}.sln --configuration Release --no-restore
      - name: Upload To Repository
        uses: actions/upload-artifact@v2
        with:
          name: PluginRepoZip
          path: ${{ env.RELEASE_DIR }}
          if-no-files-found: error
          retention-days: 1
      - name: Tag Release
        run: |
          buildVersion=$(jq -j .AssemblyVersion "${{ env.RELEASE_DIR }}/${{ env.SOLUTION_NAME }}.json")
          git tag -am "[Automated build $buildVersion]" "v$buildVersion"
          git push origin "v$buildVersion"
        shell: bash
        env:
          GIT_AUTHOR_NAME: Priscilla
          GIT_COMMITTER_NAME: Priscilla
          GIT_AUTHOR_EMAIL: noreply@ahd-creative.agency
          GIT_COMMITTER_EMAIL: noreply@ahd-creative.agency
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
         - ref: 'v*.*.*.*'
         - repository: ${{ env.XIVITA_REPO_URL }}
         - token: ${{ secrets.PAT }}
      - name: Download Build
        uses: actions/download-artifact@v2
        with:
          name: PluginRepoZip
          path: plugins/${{ env.INTERNAL_NAME }}
      - name: Commit Changes
        uses: EndBug/add-and-commit@v7
        with:
          add: plugins/
          branch: main
          pathspec_error_handling: exitImmediately
          author_name: Priscilla
          author_email: noreply@ahd-creative.agency
          message: Update ${{ env.INTERNAL_NAME }}